import { Challenge } from '../types/game';
import { SaveManager } from './SaveManager';

export const ALL_CHALLENGES: Challenge[] = [
  {
    id: 'c1',
    title: 'First Goal',
    description: 'Score 1 goal in 3 attempts.',
    difficulty: 'STREET',
    targetGoals: 1,
    maxAttempts: 3,
    wallSize: 0,
    stadium: 'DAY',
    weather: 'CLEAR',
    stars: 1,
    completed: false,
  },
  {
    id: 'c2',
    title: 'Wall Breaker',
    description: 'Score 2 goals in 4 attempts over a 2-man wall.',
    difficulty: 'STREET',
    targetGoals: 2,
    maxAttempts: 4,
    wallSize: 2,
    stadium: 'DAY',
    weather: 'CLEAR',
    stars: 1,
    completed: false,
  },
  {
    id: 'c3',
    title: 'Corner Hunter',
    description: 'Score into the top corner past a 3-man wall.',
    difficulty: 'PRO',
    targetGoals: 2,
    maxAttempts: 5,
    wallSize: 3,
    stadium: 'NIGHT',
    weather: 'CLEAR',
    requiresTopCorner: true,
    stars: 2,
    completed: false,
  },
  {
    id: 'c4',
    title: 'Curve Specialist',
    description: 'Score 2 curved shots around a 4-man wall.',
    difficulty: 'PRO',
    targetGoals: 2,
    maxAttempts: 4,
    wallSize: 4,
    stadium: 'NIGHT',
    weather: 'CLEAR',
    requiresCurve: true,
    stars: 2,
    completed: false,
  },
  {
    id: 'c5',
    title: 'Rainy Night Match',
    description: 'Score 3 goals in 5 attempts under heavy rain.',
    difficulty: 'PRO',
    targetGoals: 3,
    maxAttempts: 5,
    wallSize: 3,
    stadium: 'NIGHT',
    weather: 'RAIN',
    stars: 2,
    completed: false,
  },
  {
    id: 'c6',
    title: 'Legend GK Duel',
    description: 'Score 2 goals against a Legend Goalkeeper.',
    difficulty: 'LEGEND',
    targetGoals: 2,
    maxAttempts: 5,
    wallSize: 4,
    stadium: 'DAY',
    weather: 'CLEAR',
    stars: 3,
    completed: false,
  },
  {
    id: 'c7',
    title: 'African Sunset',
    description: 'Score 3 goals in 5 attempts in the African Stadium.',
    difficulty: 'PRO',
    targetGoals: 3,
    maxAttempts: 5,
    wallSize: 3,
    stadium: 'AFRICAN',
    weather: 'CLEAR',
    stars: 2,
    completed: false,
  },
  {
    id: 'c8',
    title: 'Precision Sniper',
    description: 'Score 3 top-corner goals in 6 attempts.',
    difficulty: 'LEGEND',
    targetGoals: 3,
    maxAttempts: 6,
    wallSize: 4,
    stadium: 'NIGHT',
    weather: 'CLEAR',
    requiresTopCorner: true,
    stars: 3,
    completed: false,
  },
  {
    id: 'c9',
    title: 'Street Pitch Showdown',
    description: 'Score 4 goals in 6 attempts on the Street Pitch.',
    difficulty: 'LEGEND',
    targetGoals: 4,
    maxAttempts: 6,
    wallSize: 4,
    stadium: 'STREET',
    weather: 'CLEAR',
    stars: 3,
    completed: false,
  },
  {
    id: 'c10',
    title: 'Free-Kick Master',
    description: 'Score 5 goals in 5 attempts with a 5-man wall.',
    difficulty: 'LEGEND',
    targetGoals: 5,
    maxAttempts: 5,
    wallSize: 5,
    stadium: 'NIGHT',
    weather: 'CLEAR',
    stars: 3,
    completed: false,
  },
];

export class ChallengeManager {
  public static async getChallenges(): Promise<Challenge[]> {
    const completedIds = await SaveManager.loadCompletedChallenges();
    return ALL_CHALLENGES.map(c => ({
      ...c,
      completed: completedIds.includes(c.id),
    }));
  }

  public static async markCompleted(challengeId: string): Promise<void> {
    await SaveManager.saveCompletedChallenge(challengeId);
  }
}
